version: '3.8'

services:
  venice-staking-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: venice-staking-bot
    restart: unless-stopped
    stdin_open: true  # For interactive input
    tty: true         # TTY (Teletypewriter) support
    volumes:
      - ./.env.encrypted:/app/.env.encrypted:ro  # Mount the encrypted file
      - ./bot.log:/app/bot.log  # Optional: Mount log
    environment:
      - NODE_ENV=production
    # If network needed
    # networks:
    #   - app-network

# networks:
#   app-network:
#     driver: bridge